# Generated by Django 5.0 on 2026-01-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cv_certification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='image',
        ),
    ]
